package view.Theme;

import java.awt.FlowLayout;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

@SuppressWarnings("serial")
public class CustomComboBoxTester extends JFrame {

	public CustomComboBoxTester() {

		setLayout(new FlowLayout());

		CountryComboBox customCombobox = new CountryComboBox();
		customCombobox.setEditable(true);
		customCombobox.addItems(countryList);

		add(customCombobox);

		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setSize(400, 100);
		setLocationRelativeTo(null); // center on screen
	}

	public static void main(String[] args) {
		SwingUtilities.invokeLater(new Runnable() {
			@Override
			public void run() {
				new CustomComboBoxTester().setVisible(true);
			}
		});
	}

	static public String[][] countryList = {
			{ " Afghanistan", "/img/pays/afghanistan_64.png" },
			{ " Aland islands", "/img/pays/aland_islands_64.png" },
			{ " Albania", "/img/pays/albania_64.png" },
			{ " Algeria", "/img/pays/algeria_64.png" },
			{ " American samoa", "/img/pays/american_samoa_64.png" },
			{ " Andorra", "/img/pays/andorra_64.png" },
			{ " Angola", "/img/pays/angola_64.png" },
			{ " Anguilla", "/img/pays/anguilla_64.png" },
			{ " Antarctica", "/img/pays/antarctica_64.png" },
			{ " Antigua and Barbuda", "/img/pays/antigua_and_barbuda_64.png" },
			{ " Argentina", "/img/pays/argentina_64.png" },
			{ " Armenia", "/img/pays/armenia_64.png" },
			{ " Aruba", "/img/pays/aruba_64.png" },
			{ " Australia", "/img/pays/australia_64.png" },
			{ " Austria", "/img/pays/austria_64.png" },
			{ " Azerbaijan", "/img/pays/azerbaijan_64.png" },
			{ " Bahamas", "/img/pays/bahamas_64.png" },
			{ " Bahrain", "/img/pays/bahrain_64.png" },
			{ " Bangladesh", "/img/pays/bangladesh_64.png" },
			{ " Barbados", "/img/pays/barbados_64.png" },
			{ " Belarus", "/img/pays/belarus_64.png" },
			{ " Belgium", "/img/pays/belgium_64.png" },
			{ " Belize", "/img/pays/belize_64.png" },
			{ " Benin", "/img/pays/benin_64.png" },
			{ " Bermuda", "/img/pays/bermuda_64.png" },
			{ " Bhutan", "/img/pays/bhutan_64.png" },
			{ " Bolivia", "/img/pays/bolivia_64.png" },
			{ " Bonaire", "/img/pays/bonaire_64.png" },
			{ " Bosnia and Herzegovina", "/img/pays/bosnia_and_herzegovina_64.png" },
			{ " Botswana", "/img/pays/botswana_64.png" },
			{ " Bouvet island", "/img/pays/bouvet_island_64.png" },
			{ " Brazil", "/img/pays/brazil_64.png" },
			{ " British indian", "/img/pays/british_indian_ocean_territory_64.png" },
			{ " Brunei", "/img/pays/brunei_64.png" },
			{ " Bulgaria", "/img/pays/bulgaria_64.png" },
			{ " Burkina faso", "/img/pays/burkina_faso_64.png" },
			{ " Burundi", "/img/pays/burundi_64.png" },
			{ " Cambodia", "/img/pays/cambodia_64.png" },
			{ " Cameroon", "/img/pays/cameroon_64.png" },
			{ " Canada", "/img/pays/canada_64.png" },
			{ " Cape verde", "/img/pays/cape_verde_64.png" },
			{ " Cayman islands", "/img/pays/cayman_islands_64.png" },
			{ " Central african", "/img/pays/central_african_republic_64.png" },
			{ " Chad", "/img/pays/chad_64.png" },
			{ " Chile", "/img/pays/chile_64.png" },
			{ " China", "/img/pays/china_64.png" },
			{ " Christmas island", "/img/pays/christmas_island_64.png" },
			{ " Cocos islands", "/img/pays/cocos_islands_64.png" },
			{ " Colombia", "/img/pays/colombia_64.png" },
			{ " Comoros", "/img/pays/comoros_64.png" },
			{ " Cook islands", "/img/pays/cook_islands_64.png" },
			{ " Costa rica", "/img/pays/costa_rica_64.png" },
			{ " Cote divoire", "/img/pays/cote_d_Ivoire_64.png" },
			{ " Croatia", "/img/pays/croatia_64.png" },
			{ " Cuba", "/img/pays/cuba_64.png" },
			{ " Curacao", "/img/pays/curacao_64.png" },
			{ " Cyprus", "/img/pays/cyprus_64.png" },
			{ " Czech republic", "/img/pays/czech_republic_64.png" },
			{ " Democratic of congo", "/img/pays/democratic_republic_of_the_congo_64.png" },
			{ " Denmark", "/img/pays/denmark_64.png" },
			{ " Djibouti", "/img/pays/djibouti_64.png" },
			{ " Dominica", "/img/pays/dominica_64.png" },
			{ " Dominican republic", "/img/pays/dominican_republic_64.png" },
			{ " East timor", "/img/pays/east_timor_64.png" },
			{ " Ecuador", "/img/pays/ecuador_64.png" },
			{ " Egypt", "/img/pays/egypt_64.png" },
			{ " El_salvador", "/img/pays/el_salvador_64.png" },
			{ " England", "/img/pays/england_64.png" },
			{ " Equatorial guinea", "/img/pays/equatorial_guinea_64.png" },
			{ " Eritrea", "/img/pays/eritrea_64.png" },
			{ " Estonia", "/img/pays/estonia_64.png" },
			{ " Ethiopia", "/img/pays/ethiopia_64.png" },
			{ " European union", "/img/pays/european_union_64.png" },
			{ " Falkland islands", "/img/pays/falkland_islands_64.png" },
			{ " Faroe islands", "/img/pays/faroe_islands_64.png" },
			{ " Fiji", "/img/pays/fiji_64.png" },
			{ " Finland", "/img/pays/finland_64.png" },
			{ " France", "/img/pays/france_64.png" },
			{ " French guiana", "/img/pays/french_guiana_64.png" },
			{ " French polynesia", "/img/pays/french_polynesia_64.png" },
			{ " French southern", "/img/pays/french_southern_territories_64.png" },
			{ " Gabon", "/img/pays/gabon_64.png" },
			{ " Gambia", "/img/pays/gambia_64.png" },
			{ " Georgia", "/img/pays/georgia_64.png" },
			{ " Germany", "/img/pays/germany_64.png" },
			{ " Ghana", "/img/pays/ghana_64.png" },
			{ " Gibraltar", "/img/pays/gibraltar_64.png" },
			{ " Greece", "/img/pays/greece_64.png" },
			{ " Greenland", "/img/pays/greenland_64.png" },
			{ " Grenada", "/img/pays/grenada_64.png" },
			{ " Guadeloupe", "/img/pays/guadeloupe_64.png" },
			{ " Guam", "/img/pays/guam_64.png" },
			{ " Guatemala", "/img/pays/guatemala_64.png" },
			{ " Guernsey", "/img/pays/guernsey_64.png" },
			{ " Guinea", "/img/pays/guinea_64.png" },
			{ " Guinea bissau", "/img/pays/guinea_bissau_64.png" },
			{ " Guyana", "/img/pays/guyana_64.png" },
			{ " Haiti", "/img/pays/haiti_64.png" },
			{ " Heard island", "/img/pays/heard_island_and_mcdonald_islands_64.png" },
			{ " Honduras", "/img/pays/honduras_64.png" },
			{ " Hong kong", "/img/pays/hong_kong_64.png" },
			{ " Hungary", "/img/pays/hungary_64.png" },
			{ " Iceland", "/img/pays/iceland_64.png" },
			{ " India", "/img/pays/india_64.png" },
			{ " Indonesia", "/img/pays/indonesia_64.png" },
			{ " Iran", "/img/pays/iran_64.png" },
			{ " Iraq", "/img/pays/iraq_64.png" },
			{ " Ireland", "/img/pays/ireland_64.png" },
			{ " Isle of man", "/img/pays/isle_of_man_64.png" },
			{ " Italy", "/img/pays/italy_64.png" },
			{ " Jamaica", "/img/pays/jamaica_64.png" },
			{ " Japan", "/img/pays/japan_64.png" },
			{ " Jersey", "/img/pays/jersey_64.png" },
			{ " Jordan", "/img/pays/jordan_64.png" },
			{ " Kazakhstan", "/img/pays/kazakhstan_64.png" },
			{ " Kenya", "/img/pays/kenya_64.png" },
			{ " Kiribati", "/img/pays/kiribati_64.png" },
			{ " Korea north", "/img/pays/korea_north_64.png" },
			{ " Korea south", "/img/pays/korea_south_64.png" },
			{ " Kosovo", "/img/pays/kosovo_64.png" },
			{ " Kuwait", "/img/pays/kuwait_64.png" },
			{ " Kyrgyzstan", "/img/pays/kyrgyzstan_64.png" },
			{ " Laos", "/img/pays/laos_64.png" },
			{ " Latvia", "/img/pays/latvia_64.png" },
			{ " Lebanon", "/img/pays/lebanon_64.png" },
			{ " Lesotho", "/img/pays/lesotho_64.png" },
			{ " Liberia", "/img/pays/liberia_64.png" },
			{ " Libya", "/img/pays/libya_64.png" },
			{ " Liechtenstein", "/img/pays/liechtenstein_64.png" },
			{ " Lithuania", "/img/pays/lithuania_64.png" },
			{ " Luxembourg", "/img/pays/luxembourg_64.png" },
			{ " Macao", "/img/pays/macao_64.png" },
			{ " Macedonia", "/img/pays/macedonia_64.png" },
			{ " Madagascar", "/img/pays/madagascar_64.png" },
			{ " Malawi", "/img/pays/malawi_64.png" },
			{ " Malaysia", "/img/pays/malaysia_64.png" },
			{ " Maldives", "/img/pays/maldives_64.png" },
			{ " Mali", "/img/pays/mali_64.png" },
			{ " Malta", "/img/pays/malta_64.png" },
			{ " Marshall islands", "/img/pays/marshall_islands_64.png" },
			{ " Martinique", "/img/pays/martinique_64.png" },
			{ " Mauritania", "/img/pays/mauritania_64.png" },
			{ " Mauritius", "/img/pays/mauritius_64.png" },
			{ " Mayotte", "/img/pays/mayotte_64.png" },
			{ " Mexico", "/img/pays/mexico_64.png" },
			{ " Micronesia", "/img/pays/micronesia_64.png" },
			{ " Moldova", "/img/pays/moldova_64.png" },
			{ " Monaco", "/img/pays/monaco_64.png" },
			{ " Mongolia", "/img/pays/mongolia_64.png" },
			{ " Montenegro", "/img/pays/montenegro_64.png" },
			{ " Montserrat", "/img/pays/montserrat_64.png" },
			{ " Morocco", "/img/pays/morocco_64.png" },
			{ " Mozambique", "/img/pays/mozambique_64.png" },
			{ " Myanmar", "/img/pays/myanmar_64.png" },
			{ " Namibia", "/img/pays/namibia_64.png" },
			{ " Nauru", "/img/pays/nauru_64.png" },
			{ " Nepal", "/img/pays/nepal_64.png" },
			{ " Netherlands", "/img/pays/netherlands_64.png" },
			{ " New caledonia", "/img/pays/new_caledonia_64.png" },
			{ " New zealand", "/img/pays/new_zealand_64.png" },
			{ " Nicaragua", "/img/pays/nicaragua_64.png" },
			{ " Niger", "/img/pays/niger_64.png" },
			{ " Nigeria", "/img/pays/nigeria_64.png" },
			{ " Niue", "/img/pays/niue_64.png" },
			{ " Norfolk island", "/img/pays/norfolk_island_64.png" },
			{ " Northern mariana_islands", "/img/pays/northern_mariana_islands_64.png" },
			{ " Norway", "/img/pays/norway_64.png" },
			{ " Oman", "/img/pays/oman_64.png" },
			{ " Pakistan", "/img/pays/pakistan_64.png" },
			{ " Palau", "/img/pays/palau_64.png" },
			{ " Palestinian territory", "/img/pays/palestinian_territory_64.png" },
			{ " Panama", "/img/pays/panama_64.png" },
			{ " Papua new guinea", "/img/pays/papua_new_guinea_64.png" },
			{ " Paraguay", "/img/pays/paraguay_64.png" },
			{ " Peru", "/img/pays/peru_64.png" },
			{ " Philippines", "/img/pays/philippines_64.png" },
			{ " Pitcairn islands", "/img/pays/pitcairn_islands_64.png" },
			{ " Poland", "/img/pays/poland_64.png" },
			{ " Portugal", "/img/pays/portugal_64.png" },
			{ " Puerto rico", "/img/pays/puerto_rico_64.png" },
			{ " Qatar", "/img/pays/qatar_64.png" },
			{ " Republic of china", "/img/pays/republic_of_china_64.png" },
			{ " Republic of_the congo", "/img/pays/republic_of_the_congo_64.png" },
			{ " Reunion", "/img/pays/reunion_64.png" },
			{ " Romania", "/img/pays/romania_64.png" },
			{ " Russia", "/img/pays/russia_64.png" },
			{ " Rwanda", "/img/pays/rwanda_64.png" },
			{ " Saint barthelemy", "/img/pays/saint_barthelemy_64.png" },
			{ " Saint helena", "/img/pays/saint_helena_64.png" },
			{ " Saint kitts", "/img/pays/saint_kitts_and_nevis_64.png" },
			{ " Saint lucia", "/img/pays/saint_lucia_64.png" },
			{ " Saint martin", "/img/pays/saint_martin_64.png" },
			{ " Saint pierre", "/img/pays/saint_pierre_and_miquelon_64.png" },
			{ " Saint vincent", "/img/pays/saint_vincent_and_the_grenadines_64.png" },
			{ " Samoa", "/img/pays/samoa_64.png" },
			{ " San marino", "/img/pays/san_marino_64.png" },
			{ " Sao tome", "/img/pays/sao_tome_and_principe_64.png" },
			{ " Saudi arabia", "/img/pays/saudi_arabia_64.png" },
			{ " Scotland", "/img/pays/scotland_64.png" },
			{ " Senegal", "/img/pays/senegal_64.png" },
			{ " Serbia", "/img/pays/serbia_64.png" },
			{ " Seychelles", "/img/pays/seychelles_64.png" },
			{ " Sierra leone", "/img/pays/sierra_leone_64.png" },
			{ " Singapore", "/img/pays/singapore_64.png" },
			{ " Sint maarten", "/img/pays/sint_maarten_64.png" },
			{ " Slovakia", "/img/pays/slovakia_64.png" },
			{ " Slovenia", "/img/pays/slovenia_64.png" },
			{ " Solomon islands", "/img/pays/solomon_islands_64.png" },
			{ " Somalia", "/img/pays/somalia_64.png" },
			{ " South africa", "/img/pays/south_africa_64.png" },
			{ " South georgia", "/img/pays/south_georgia_and_the_south_sandwich_islands_64.png" },
			{ " South sudan", "/img/pays/south_sudan_64.png" },
			{ " Spain", "/img/pays/spain_64.png" },
			{ " Sri lanka", "/img/pays/sri_lanka_64.png" },
			{ " Sudan", "/img/pays/sudan_64.png" },
			{ " Suriname", "/img/pays/suriname_64.png" },
			{ " Svalbard", "/img/pays/svalbard_and_jan_mayen_64.png" },
			{ " Swaziland", "/img/pays/swaziland_64.png" },
			{ " Sweden", "/img/pays/sweden_64.png" },
			{ " Switzerland", "/img/pays/switzerland_64.png" },
			{ " Syria", "/img/pays/syria.png" },
			{ " Tajikistan", "/img/pays/tajikistan_64.png" },
			{ " Tanzania", "/img/pays/tanzania_64.png" },
			{ " Thailand", "/img/pays/thailand_64.png" },
			{ " Togo", "/img/pays/togo_64.png" },
			{ " Tokelau", "/img/pays/tokelau_64.png" },
			{ " Tonga", "/img/pays/tonga_64.png" },
			{ " Trinidad and tobago", "/img/pays/trinidad_and_tobago_64.png" },
			{ " Tunisia", "/img/pays/tunisia_64.png" },
			{ " Turkey", "/img/pays/turkey_64.png" },
			{ " Turkmenistan", "/img/pays/turkmenistan_64.png" },
			{ " Turks and caicos", "/img/pays/turks_and_caicos_islands_64.png" },
			{ " Tuvalu", "/img/pays/tuvalu_64.png" },
			{ " Uganda", "/img/pays/uganda_64.png" },
			{ " Ukraine", "/img/pays/ukraine_64.png" },
			{ " United arab emirates", "/img/pays/united_arab_emirates_64.png" },
			{ " United kingdom", "/img/pays/united_kingdom_64.png" },
			{ " United states", "/img/pays/united_states_of_america_64.png" },
			{ " Uruguay", "/img/pays/uruguay_64.png" },
			{ " Ussr", "/img/pays/ussr_64.png" },
			{ " Uzbekistan", "/img/pays/uzbekistan_64.png" },
			{ " Vanuatu", "/img/pays/vanuatu_64.png" },
			{ " Vatican city", "/img/pays/vatican_city_64.png" },
			{ " Venezuela", "/img/pays/venezuela_64.png" },
			{ " Vietnam", "/img/pays/vietnam_64.png" },
			{ " Virgin islands british", "/img/pays/virgin_islands_british_64.png" },
			{ " Virgin islands us", "/img/pays/virgin_islands_us_64.png" },
			{ " Wales", "/img/pays/wales_64.png" },
			{ " Wallis and futuna", "/img/pays/wallis_and_futuna_64.png" },
			{ " Western sahara", "/img/pays/western_sahara_64.png" },
			{ " Yemen", "/img/pays/yemen_64.png" },
			{ " Zambia", "/img/pays/zambia_64.png" },
			{ " Zimbabwe", "/img/pays/zimbabwe_64.png" },

	};
}